### ISSUE TITLE
flip chat bubbles

### ISSUE THREAD

**Issue by ericmigi** [saad100104006/NovaChat#3]
Chat bubbles are on the wrong side of the screen. messages from 'me' should be on the right side, from 'other' person is on left side

![Screenshot_20191102-200831_Nova Chat](https://user-images.githubusercontent.com/1048265/68079865-e97d8e00-fdad-11e9-9012-9907c38d7e23.jpg)

**Comment by saad100104006** [comment]
fixed this issue
