### ISSUE TITLE
Group messages are missing sender name

### ISSUE THREAD

**Issue by ericmigi** [saad100104006/NovaChat#4]
sender name is not displayed next to messages in group chats. eg no names here

![Screenshot_20191102-201114_Nova Chat](https://user-images.githubusercontent.com/1048265/68079872-0c0fa700-fdae-11e9-9fff-91bea63780fa.jpg)

But in RiotX there are names

![Screenshot_20191102-201155_RiotX](https://user-images.githubusercontent.com/1048265/68079870-074af300-fdae-11e9-9202-6588bad8c7dd.jpg)

**Comment by saad100104006** [comment]
![74693190_2369421986707604_5183963597138558976_n](https://user-images.githubusercontent.com/8910479/68212672-3195ee00-0004-11ea-925a-1d7ece064788.png)

Updated @ericmigi
