### ISSUE TITLE
spacing is wrong in chat view

### ISSUE THREAD

**Issue by ericmigi** [saad100104006/NovaChat#5]
Too much space on left, should be more left-justified like in the Figma.
![Screenshot_20191102-200750_Nova Chat](https://user-images.githubusercontent.com/1048265/68079888-598c1400-fdae-11e9-92c6-152fb6295e7d.jpg)

also the right edge of 'other' persons messages should be closer to the right, like in Whatsapp

![Screenshot_20191102-201126_WhatsApp](https://user-images.githubusercontent.com/1048265/68079885-52fd9c80-fdae-11e9-9aff-4b88966fe018.jpg)

**Comment by saad100104006** [comment]
![75552963_2320395514939145_8322193606441959424_n](https://user-images.githubusercontent.com/8910479/68212644-217e0e80-0004-11ea-8236-4a723893f153.png)

Please check this @ericmigi
