### ISSUE TITLE
delete this 1 pixel line at bottom of chat view

### ISSUE THREAD

**Issue by ericmigi** [saad100104006/NovaChat#6]
![Screenshot_20191102-200707_Nova Chat](https://user-images.githubusercontent.com/1048265/68079895-6f013e00-fdae-11e9-87f8-372bdd28a3b3.jpg)

**Comment by saad100104006** [comment]
![74614822_2381508795493219_8762790713378209792_n](https://user-images.githubusercontent.com/8910479/68212581-001d2280-0004-11ea-8fbe-8f0a16b7f2dc.png)

**Comment by saad100104006** [comment]
updated and improved @ericmigi
